version: '3'

services:
   server:
     image: ghcr.io/poeschl/shoreline:latest
#     ports:
#       - "1234:1234"
#       - "1235:1235"
#       - "5900:5900"
     network_mode: host # Without this the ports need to be uncommented
     command: -w 1920 -h 1080
     restart: always
